import { useEffect, useState } from 'react';
import '../../components/base.css';
import '../../components/layout.css';
import Navbar from '../../components/Navbar';
import LandingFooter from '../../components/Footer';

const SECTIONS = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    content: [
      { subtitle: "Agreement", text: 'By accessing or using this platform ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, you may not access or use the Service. These Terms apply to all users, including visitors, registered users, and paying subscribers.' },
      { subtitle: "Eligibility", text: "You must be at least 13 years old (or 16 in the European Economic Area) to use the Service. By using this platform, you represent and warrant that you meet these age requirements and have the legal capacity to enter into these Terms." },
    ],
  },
  {
    id: "description",
    title: "Description of Service",
    content: [
      { subtitle: "What We Provide", text: "Nothric provides an AI-powered platform that enables users to interact with large language models, generate content, analyze information, and complete productivity tasks. The specific features available depend on your subscription plan." },
      { subtitle: "Service Changes", text: "We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time. We will provide reasonable notice of material changes where possible. We are not liable to you or any third party for any modification, suspension, or discontinuation of the Service." },
      { subtitle: "Beta Features", text: "We may offer beta or experimental features that are not yet generally available. These features are provided 'as is' without any warranty and may be discontinued at any time without notice." },
    ],
  },
  {
    id: "accounts",
    title: "User Accounts",
    content: [
      { subtitle: "Account Responsibility", text: "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account." },
      { subtitle: "Accurate Information", text: "You agree to provide accurate, current, and complete information when creating your account and to update such information to keep it accurate, current, and complete." },
      { subtitle: "One Account Per User", text: "Each person may maintain only one account. Creating multiple accounts to circumvent usage limits, suspensions, or other restrictions is prohibited and may result in termination of all associated accounts." },
    ],
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    content: [
      { subtitle: "Permitted Use", text: "You may use Nothric only for lawful purposes and in accordance with these Terms. You agree to use the Service in a manner consistent with applicable laws and regulations." },
      { subtitle: "Prohibited Activities", text: "You may not: (a) use the Service to generate, distribute, or facilitate illegal content; (b) attempt to reverse-engineer, decompile, or extract the underlying models; (c) use the Service to impersonate any person or entity; (d) transmit malware, viruses, or any harmful code; (e) scrape or harvest data from the Service without authorization; or (f) resell or commercialize access to the Service without our written consent." },
      { subtitle: "AI-Specific Restrictions", text: "You may not use Nothric to generate content that is defamatory, sexually explicit, or that promotes violence, discrimination, or illegal activities. You may not use automated systems to access the Service in ways that exceed reasonable usage." },
    ],
  },
  {
    id: "ai-content",
    title: "AI-Generated Content",
    content: [
      { subtitle: "Nature of AI Output", text: "Nothric uses large language models that generate probabilistic outputs. AI-generated content may contain inaccuracies, errors, or outdated information. You are responsible for reviewing, validating, and exercising independent judgment about any AI-generated content before relying on it." },
      { subtitle: "Ownership of Outputs", text: "Subject to these Terms, outputs generated by Nothric based on your prompts are yours to use. You grant us a limited license to process your inputs to deliver the Service. We do not claim ownership of your content." },
      { subtitle: "No Professional Advice", text: "AI-generated content does not constitute legal, medical, financial, psychological, or any other professional advice. Always consult a qualified professional for matters requiring expert judgment." },
    ],
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    content: [
      { subtitle: "Our Property", text: "The Service, including its design, code, AI models, branding, and all related intellectual property, is owned by Nothric and protected by copyright, trademark, and other laws. Nothing in these Terms grants you a right to use our trademarks or branding without prior written permission." },
      { subtitle: "Your Content", text: "You retain ownership of all content you submit to the Service. By submitting content, you grant Nothric a worldwide, non-exclusive, royalty-free license to process your content solely to operate and improve the Service, subject to our Privacy Policy." },
      { subtitle: "Feedback", text: "If you provide feedback, suggestions, or ideas about the Service, you grant us the right to use such feedback without restriction or compensation to you." },
    ],
  },
  {
    id: "payment",
    title: "Subscriptions & Payment",
    content: [
      { subtitle: "Subscription Plans", text: "Certain features of Nothric require a paid subscription. Subscription fees are billed in advance on a monthly or annual basis and are non-refundable except as required by applicable law or as expressly stated in our Refund Policy." },
      { subtitle: "Billing", text: "You authorize us to charge your payment method for the applicable subscription fees. If payment fails, we may suspend access to paid features until payment is resolved. Prices are subject to change with 30 days' advance notice." },
      { subtitle: "Free Tier", text: "Free-tier access is provided at our discretion and may be modified or discontinued at any time. Usage on the free tier is subject to rate limits that may change without notice." },
    ],
  },
  {
    id: "disclaimers",
    title: "Disclaimers & Limitation of Liability",
    content: [
      { subtitle: "As-Is Basis", text: 'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE FROM VIRUSES OR OTHER HARMFUL COMPONENTS.' },
      { subtitle: "Limitation of Liability", text: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NOTHRIC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES." },
      { subtitle: "Cap on Liability", text: "Our total aggregate liability to you for any claims arising out of or related to these Terms or the Service shall not exceed the greater of (a) the amounts paid by you to Nothric in the 12 months preceding the claim, or (b) USD $100." },
    ],
  },
  {
    id: "termination",
    title: "Termination",
    content: [
      { subtitle: "By You", text: "You may stop using the Service and cancel your account at any time by accessing your account settings or contacting support." },
      { subtitle: "By Us", text: "We may suspend or terminate your access to the Service at any time if you violate these Terms, engage in fraudulent activity, or for any other reason at our sole discretion with reasonable notice where practicable." },
      { subtitle: "Effect of Termination", text: "Upon termination, your right to access and use the Service will immediately cease. Provisions that by their nature should survive termination (including intellectual property, disclaimers, and limitation of liability) will survive." },
    ],
  },
  {
    id: "governing-law",
    title: "Governing Law & Disputes",
    content: [
      { subtitle: "Governing Law", text: "These Terms are governed by the laws of the State of California, United States, without regard to conflict of law principles." },
      { subtitle: "Dispute Resolution", text: "Any dispute arising out of or related to these Terms or the Service shall first be addressed through good-faith negotiation. If unresolved, disputes shall be settled by binding arbitration in San Francisco, California, under the rules of the American Arbitration Association, except that either party may seek injunctive relief in a court of competent jurisdiction." },
      { subtitle: "Class Action Waiver", text: "You agree that any dispute resolution proceeding will be conducted only on an individual basis and not as a class, consolidated, or representative action." },
    ],
  },
  {
    id: "general",
    title: "General Provisions",
    content: [
      { subtitle: "Entire Agreement", text: "These Terms, together with our Privacy Policy, constitute the entire agreement between you and Nothric regarding the Service and supersede all prior agreements." },
      { subtitle: "Severability", text: "If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will remain in full force and effect." },
      { subtitle: "Contact", text: "For questions about these Terms, contact us at legal@endurance.ai or the Nothric Team, 100 Technology Square, San Francisco, CA 94107." },
    ],
  },
];

export default function TermsPage() {
  const [activeSection, setActiveSection] = useState<string>('');

  useEffect(() => {
    document.title = 'Terms of Use | Nothric';
  }, []);

  // IntersectionObserver to sync scroll position with sidebar highlights
  useEffect(() => {
    const observerOptions = {
      root: null,
      rootMargin: '-10% 0px -75% 0px',
      threshold: 0
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          setActiveSection(entry.target.id);
        }
      });
    }, observerOptions);

    SECTIONS.forEach((s) => {
      const el = document.getElementById(s.id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  return (
    <div
      className="privacy-terms-container"
      style={{
        backgroundColor: "#09090a",
        color: "#f4f4f5",
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', sans-serif"
      }}
    >
      <Navbar />

      <div style={{
        maxWidth: "1100px",
        margin: "0 auto",
        padding: "120px 32px 80px 32px",
        display: "grid",
        gridTemplateColumns: "240px 1fr",
        gap: "64px",
        alignItems: "start",
        boxSizing: "border-box"
      }}>
        {/* Sidebar */}
        <nav className="privacy-terms-sidebar" style={{ position: "sticky", top: "80px" }}>
          <p style={{
            fontSize: "10.5px",
            fontWeight: "600",
            color: "#ffffff",
            textTransform: "uppercase",
            letterSpacing: "0.08em",
            marginBottom: "12px",
            margin: "0 0 12px 0",
            display: "flex",
            alignItems: "center",
            gap: "6px"
          }}>
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 0.8 }}>
              <line x1="8" y1="6" x2="21" y2="6" />
              <line x1="8" y1="12" x2="21" y2="12" />
              <line x1="8" y1="18" x2="21" y2="18" />
              <line x1="3" y1="6" x2="3.01" y2="6" strokeWidth="3" />
              <line x1="3" y1="12" x2="3.01" y2="12" strokeWidth="3" />
              <line x1="3" y1="18" x2="3.01" y2="18" strokeWidth="3" />
            </svg>
            On this page
          </p>
          <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "8px" }}>
            {SECTIONS.map((s) => {
              const isActive = activeSection === s.id;
              return (
                <li key={s.id}>
                  <a
                    href={`#${s.id}`}
                    style={{
                      display: "block",
                      fontSize: "13px",
                      color: isActive ? "#ef4444" : "#71717a",
                      borderLeft: `2px solid ${isActive ? "#ef4444" : "transparent"}`,
                      textDecoration: "none",
                      lineHeight: "1.4",
                      padding: "4px 0 4px 12px",
                      transition: "all 0.2s"
                    }}
                    onMouseEnter={(e) => {
                      if (!isActive) {
                        e.currentTarget.style.color = "#ef4444";
                        e.currentTarget.style.borderLeftColor = "#ef4444";
                      }
                    }}
                    onMouseLeave={(e) => {
                      if (!isActive) {
                        e.currentTarget.style.color = "#71717a";
                        e.currentTarget.style.borderLeftColor = "transparent";
                      }
                    }}
                  >
                    {s.title}
                  </a>
                </li>
              );
            })}
          </ul>
        </nav>

        {/* Content */}
        <main style={{ minWidth: 0 }}>
          <div className="privacy-terms-hero" style={{ marginBottom: "48px", paddingBottom: "32px", borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
            <div style={{ display: "inline-flex", alignItems: "center", gap: "6px", background: "rgba(255,255,255,0.06)", borderRadius: "6px", padding: "4px 10px", marginBottom: "16px" }}>
              <span style={{ fontSize: "11px", fontWeight: "500", color: "#a1a1aa" }}>Effective: July 17, 2026</span>
            </div>
            <h1 style={{ fontSize: "36px", fontWeight: "600", fontFamily: "'Source Serif 4', Georgia, serif", letterSpacing: "-0.02em", color: "#ffffff", margin: "0 0 14px 0", lineHeight: 1.2 }}>
              Terms of Service
            </h1>
            <p style={{ fontSize: "15px", color: "#a1a1aa", margin: 0, maxWidth: "620px", lineHeight: 1.7 }}>
              Please read these Terms carefully before using our platform. They govern your access to and use of our platform, products, and services.
            </p>
          </div>

          {SECTIONS.map((section, i) => (
            <section
              key={section.id}
              id={section.id}
              className="privacy-terms-section"
              style={{
                marginBottom: "40px",
                paddingBottom: "40px",
                borderBottom: i < SECTIONS.length - 1 ? "1px solid rgba(255,255,255,0.08)" : "none"
              }}
            >
              <h2 style={{ fontSize: "18px", fontWeight: "700", letterSpacing: "-0.01em", color: "#ffffff", marginBottom: "20px", display: "flex", alignItems: "center", gap: "10px", margin: "0 0 20px 0" }}>
                <span style={{
                  display: "inline-flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontSize: "11px",
                  fontWeight: "bold",
                  color: "#ef4444",
                  flexShrink: 0,
                  width: "24px",
                  height: "24px",
                  borderRadius: "6px",
                  background: "rgba(239, 68, 68, 0.12)"
                }}>
                  {i + 1}
                </span>
                {section.title}
              </h2>
              {section.content.map((block) => (
                <div key={block.subtitle} style={{ marginBottom: "20px" }}>
                  <h3 style={{ fontSize: "13px", fontWeight: "700", color: "#f4f4f5", margin: "0 0 6px 0", letterSpacing: "0.01em" }}>{block.subtitle}</h3>
                  <p style={{ fontSize: "14px", color: "#a1a1aa", margin: 0, lineHeight: 1.72 }}>{block.text}</p>
                </div>
              ))}
            </section>
          ))}
        </main>
      </div>

      <LandingFooter />
    </div>
  );
}
